Plural Sight/Fundamentals/MainSolution/TicTacToe/Models/GameInvitationModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TicTacToe.Models
{
    public class GameInvitationModel
    {
        public Guid Id { get; set; }

        public string EmailTo { get; set; }

        public string InvitedBy { get; set; }

        public bool IsConfirmed { get; set; }

        public DateTime ConfirmationDate { get; set; }
    }
}

Plural Sight/Fundamentals/MainSolution/TicTacToe/Models/UserModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TicTacToe.Models
{
    public class UserModel
    {
        public Guid Id { get; set; }

        [Required]
        public string FirstName { get; set; }

        [Required]
        public string LastName { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        public bool IsEmailConfirmed { get; set; }

        public DateTime? EmailConfirmationDate { get; set; }

        public int Score { get; set; }
    }
}

Plural Sight/Fundamentals/MainSolution/TicTacToe/Controllers/GameInvitationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TicTacToe.Models;
using TicTacToe.Services;

namespace TicTacToe.Controllers
{
    public class GameInvitationController : Controller
    {
        private readonly IUserService _userService;

        public GameInvitationController(IUserService userService)
        {
            _userService = userService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(Guid invitedBy)
        {
            var invitingUser = await _userService.GetUserById(invitedBy);
            var invitationModel = new GameInvitationModel
            {
                InvitedBy = invitingUser.Email
            };

            return View(invitationModel);
        }
    }
}

Plural Sight/Fundamentals/MainSolution/TicTacToe/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TicTacToe.Controllers
{
    public class HomeController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

Plural Sight/Fundamentals/MainSolution/TicTacToe/Controllers/UserRegistrationController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TicTacToe.Models;
using TicTacToe.Services;

namespace TicTacToe.Controllers
{
    public class UserRegistrationController : Controller
    {
        private readonly IUserService _userService;

        public UserRegistrationController(IUserService userService)
        {
            _userService = userService;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Index(UserModel userModel)
        {
            if (!ModelState.IsValid)
            {
                return View(userModel);
            }

            userModel.Id = Guid.NewGuid();
            await _userService.CreateUser(userModel);
            return RedirectToAction(nameof(EmailConfirmation), new { emailAddress = userModel.Email });
        }

        [HttpGet]
        public async Task<IActionResult> EmailConfirmation(string emailAddress)
        {
            var user = await _userService.GetUserByEmail(emailAddress);
            if (user?.IsEmailConfirmed == true)
            {
                return RedirectToAction(nameof(Index), nameof(GameInvitationController).Remove(nameof(GameInvitationController).IndexOf("Controller")), new { invitedBy = user.Id });
            }

            ViewBag.Email = emailAddress;
            return View();
        }
    }
}

Plural Sight/Fundamentals/MainSolution/TicTacToe/Views/Home/Index.cshtml
@{ ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml"; }
<div class="row">
    <div class="col-lg-12">
        <h2>Tic-Tac-Toe</h2>
        <div class="alert alert-info">
            <p>Tic-Tac-Toe is a two-player turn-based game.</p>
            <p>
                Two players will choose who takes the Xs and who takes the Os.
                They will then be taking turns and mark spaces in a
                3×3 grid by putting their marks, one mark per turn.
            </p>
            <p>
                A player who succeeds in placing three of his arks in a
                horizontal, vertical, or diagonal row wins the
                game.
            </p>
        </div>
        <p>
            <h3>
                Register by clicking <a asp-controller="UserRegistration" asp-view="Index">here</a>
            </h3>
        </p>
    </div>
</div>

Plural Sight/Fundamentals/MainSolution/TicTacToe/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TicTacToe</title>
    <environment include="Development">
        <link rel="stylesheet" href="/node_modules/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="/node_modules/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-testproperty="position"
              asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-smnavbar-light bg-white border-bottombox-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TicTacToe</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-rowreverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">
                                Privacy
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container body-content">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2019 - TicTacToe - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
    </div>

    <environment include="Development">
        <script src="/node_modules/jquery/dist/jquery.js"></script>
        <script src="/node_modules/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <environment include="Development">
        <script src="~/app/js/emailConfirmationEvent.js"></script>
        <script src="~/app/js/emailconfirmationprocessor.js"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Plural Sight/Fundamentals/MainSolution/TicTacToe/Views/UserRegistration/EmailConfirmation.cshtml
 
@{
    ViewData["Title"] = "EmailConfirmation";
    var email = ViewData["Email"] as string;
}

<h1>EmailConfirmation</h1>
<p>
    A confirmation email has been sent to @email. Please use the instructions given in the email message to verify the user.
</p>

@section Scripts{ 
    <script>
        $(document).ready(() => attchEmailConfirmationEvent('@email'));
    </script>
}

Plural Sight/Fundamentals/MainSolution/TicTacToe/Views/UserRegistration/Index.cshtml
@model TicTacToe.Models.UserModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<h4>UserModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Index">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
